### ISSUE TITLE
MQTT not connecting to server anymore

### ISSUE THREAD

**Issue by Rene1695** [tbnobody/OpenDTU#2787]
### What happened?

Since a couple of days, OpenDTU does not connect to my MQTT server anymore. Connection status is always marked as red. I tried restarting OpenDTU, MQTT, my mosquito server but still same issue. I checked with MQTT Explorer and the server is running fine. 

<img width="2962" height="1528" alt="Image" src="https://github.com/user-attachments/assets/aec87ad6-5243-4a6d-bae9-e8f467e3844f" />

I was not able to set the log file correctly or it didn't throw an issue regarding MQTT. Does anyone else facing similar issues? 

<img width="2962" height="1368" alt="Image" src="https://github.com/user-attachments/assets/bf7f6889-1b2c-44b9-adc0-dadcd9048c7c" />

<img width="2962" height="1406" alt="Image" src="https://github.com/user-attachments/assets/75c08579-a811-4033-943a-0ca6c3a43083" />

### To Reproduce Bug

Always disconnected

### Expected Behavior

Connection status set to green, MQTT Explorer shows data from OpenDTU

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

25.5.10

### What firmware variant (PIO Environment)?

generic

### Relevant log/trace output

```Shell

```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
- [x] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by Boldfor** [comment]
+1

Not 100% sure on the error, but I have multiple MQTT-components feeding into my openHAB, and everything is working, **except openDTU** (which has been running for 2 years without ever having a problem, ..., so it's the first time that openDTU causes problems).

**Comment by knxhm** [comment]
A packet trace (tcpdump) on the machine which runs the mosquitto server would be helpfull.
Restart the ESP32 while the trace is running.
Provide the IP of ESP32.

**Comment by Rene1695** [comment]
@knxhm ESP running on 192.168.0.50, Mosquito running on 192.168.0.4

```
Last login: Tue Aug 12 19:02:34 on ttys000
xxx@macmini ~ % sudo tcpdump -i en0 host 192.168.0.50

tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on en0, link-type EN10MB (Ethernet), snapshot length 524288 bytes
19:05:50.722673 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [S], seq 3768862841, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3979543239 ecr 0,sackOK,eol], length 0
19:05:51.294567 ARP, Announcement 192.168.0.50, length 46
19:05:51.724235 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [S], seq 3768862841, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3979544240 ecr 0,sackOK,eol], length 0
19:05:51.831603 ARP, Request who-has 192.168.0.4 tell 192.168.0.50, length 46
19:05:51.831684 ARP, Reply 192.168.0.4 is-at 14:98:77:70:af:a1 (oui Unknown), length 28
19:05:51.839538 IP 192.168.0.50.http > 192.168.0.4.50605: Flags [S.], seq 3827018596, ack 3768862842, win 5760, options [mss 1436], length 0
19:05:51.839659 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:05:51.839961 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:05:51.857500 IP 192.168.0.50.http > 192.168.0.4.50605: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:05:51.857547 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:05:51.857813 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:05:51.860123 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [S], seq 2141781348, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3190818939 ecr 0,sackOK,eol], length 0
19:05:51.871142 IP 192.168.0.50.http > 192.168.0.4.50605: Flags [F.], seq 675, ack 114, win 5647, length 0
19:05:51.871267 IP 192.168.0.4.50605 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:05:51.872538 IP 192.168.0.50.http > 192.168.0.4.50614: Flags [S.], seq 1472464277, ack 2141781349, win 5760, options [mss 1436], length 0
19:05:51.872602 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:05:51.872927 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:05:51.887845 IP 192.168.0.50.http > 192.168.0.4.50614: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:05:51.887897 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:05:51.888111 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:05:51.897361 IP 192.168.0.50.http > 192.168.0.4.50614: Flags [F.], seq 675, ack 114, win 5647, length 0
19:05:51.897638 IP 192.168.0.4.50614 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:05:59.722828 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [S], seq 77321892, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2126884694 ecr 0,sackOK,eol], length 0
19:05:59.812140 IP 192.168.0.50.http > 192.168.0.4.50653: Flags [S.], seq 3833388187, ack 77321893, win 5760, options [mss 1436], length 0
19:05:59.812342 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:05:59.812665 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:05:59.827541 IP 192.168.0.50.http > 192.168.0.4.50653: Flags [P.], seq 1:674, ack 113, win 5648, length 673: HTTP: HTTP/1.1 200 OK
19:05:59.827743 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [.], ack 674, win 65535, length 0
19:05:59.827949 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [F.], seq 113, ack 674, win 65535, length 0
19:05:59.830762 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [S], seq 347336119, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3105688081 ecr 0,sackOK,eol], length 0
19:05:59.840351 IP 192.168.0.50.http > 192.168.0.4.50653: Flags [F.], seq 674, ack 114, win 5647, length 0
19:05:59.840603 IP 192.168.0.4.50653 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:05:59.849186 IP 192.168.0.50.http > 192.168.0.4.50654: Flags [S.], seq 4102212868, ack 347336120, win 5760, options [mss 1436], length 0
19:05:59.849363 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:05:59.849721 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:05:59.866660 IP 192.168.0.50.http > 192.168.0.4.50654: Flags [P.], seq 1:674, ack 113, win 5648, length 673: HTTP: HTTP/1.1 200 OK
19:05:59.866837 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [.], ack 674, win 65535, length 0
19:05:59.867144 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [F.], seq 113, ack 674, win 65535, length 0
19:05:59.878308 IP 192.168.0.50.http > 192.168.0.4.50654: Flags [F.], seq 674, ack 114, win 5647, length 0
19:05:59.878488 IP 192.168.0.4.50654 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:06:01.148013 ARP, Request who-has mac.fritz.box tell 192.168.0.50, length 46
19:06:09.723024 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [S], seq 32898004, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2809625764 ecr 0,sackOK,eol], length 0
19:06:09.743382 IP 192.168.0.50.http > 192.168.0.4.50716: Flags [S.], seq 1606154292, ack 32898005, win 5760, options [mss 1436], length 0
19:06:09.743601 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:09.743961 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:09.760811 IP 192.168.0.50.http > 192.168.0.4.50716: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:06:09.760974 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:06:09.761554 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:06:09.763245 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [S], seq 3038922808, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 816421398 ecr 0,sackOK,eol], length 0
19:06:09.773140 IP 192.168.0.50.http > 192.168.0.4.50716: Flags [F.], seq 675, ack 114, win 5647, length 0
19:06:09.773285 IP 192.168.0.4.50716 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:06:09.782892 IP 192.168.0.50.http > 192.168.0.4.50717: Flags [S.], seq 2532019244, ack 3038922809, win 5760, options [mss 1436], length 0
19:06:09.783054 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:09.783484 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:09.800077 IP 192.168.0.50.http > 192.168.0.4.50717: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:06:09.800268 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:06:09.800561 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:06:09.812157 IP 192.168.0.50.http > 192.168.0.4.50717: Flags [F.], seq 675, ack 114, win 5647, length 0
19:06:09.812353 IP 192.168.0.4.50717 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:06:19.722121 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [S], seq 4220492016, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 1746741941 ecr 0,sackOK,eol], length 0
19:06:19.780613 IP 192.168.0.50.http > 192.168.0.4.50793: Flags [S.], seq 3908987627, ack 4220492017, win 5760, options [mss 1436], length 0
19:06:19.780805 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:19.781752 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:19.794391 IP 192.168.0.50.http > 192.168.0.4.50793: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:06:19.794519 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:06:19.794804 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:06:19.798557 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [S], seq 3297560159, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2722789549 ecr 0,sackOK,eol], length 0
19:06:19.804724 IP 192.168.0.50.http > 192.168.0.4.50793: Flags [F.], seq 675, ack 114, win 5647, length 0
19:06:19.804828 IP 192.168.0.4.50793 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:06:19.810883 IP 192.168.0.50.http > 192.168.0.4.50794: Flags [S.], seq 3810016183, ack 3297560160, win 5760, options [mss 1436], length 0
19:06:19.810959 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:19.812075 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:19.825598 IP 192.168.0.50.http > 192.168.0.4.50794: Flags [P.], seq 1:675, ack 113, win 5648, length 674: HTTP: HTTP/1.1 200 OK
19:06:19.825682 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [.], ack 675, win 65535, length 0
19:06:19.825894 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [F.], seq 113, ack 675, win 65535, length 0
19:06:19.834935 IP 192.168.0.50.http > 192.168.0.4.50794: Flags [F.], seq 675, ack 114, win 5647, length 0
19:06:19.835113 IP 192.168.0.4.50794 > 192.168.0.50.http: Flags [.], ack 676, win 65535, length 0
19:06:28.768333 ARP, Announcement 192.168.0.50, length 46
19:06:29.511414 ARP, Request who-has mac.fritz.box tell 192.168.0.50, length 46
19:06:29.608487 ARP, Request who-has mac.fritz.box tell 192.168.0.50, length 46
19:06:29.722876 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [S], seq 134358536, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 1037423917 ecr 0,sackOK,eol], length 0
19:06:29.813613 ARP, Request who-has 192.168.0.4 tell 192.168.0.50, length 46
19:06:29.813706 ARP, Reply 192.168.0.4 is-at 14:98:77:70:af:a1 (oui Unknown), length 28
19:06:29.819763 IP 192.168.0.50.http > 192.168.0.4.50869: Flags [S.], seq 2921735465, ack 134358537, win 5760, options [mss 1436], length 0
19:06:29.819891 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:29.820218 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:29.841799 IP 192.168.0.50.http > 192.168.0.4.50869: Flags [P.], seq 1:663, ack 113, win 5648, length 662: HTTP: HTTP/1.1 200 OK
19:06:29.841858 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [.], ack 663, win 65535, length 0
19:06:29.842100 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [F.], seq 113, ack 663, win 65535, length 0
19:06:29.844248 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [S], seq 3620500701, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 1818690976 ecr 0,sackOK,eol], length 0
19:06:29.865630 IP 192.168.0.50.http > 192.168.0.4.50869: Flags [F.], seq 663, ack 114, win 5647, length 0
19:06:29.865634 IP 192.168.0.50.http > 192.168.0.4.50870: Flags [S.], seq 1464546432, ack 3620500702, win 5760, options [mss 1436], length 0
19:06:29.865724 IP 192.168.0.4.50869 > 192.168.0.50.http: Flags [.], ack 664, win 65535, length 0
19:06:29.865851 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:29.865992 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:29.884957 IP 192.168.0.50.http > 192.168.0.4.50870: Flags [P.], seq 1:663, ack 113, win 5648, length 662: HTTP: HTTP/1.1 200 OK
19:06:29.885065 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [.], ack 663, win 65535, length 0
19:06:29.885430 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [F.], seq 113, ack 663, win 65535, length 0
19:06:29.892405 IP 192.168.0.50.http > 192.168.0.4.50870: Flags [F.], seq 663, ack 114, win 5647, length 0
19:06:29.892582 IP 192.168.0.4.50870 > 192.168.0.50.http: Flags [.], ack 664, win 65535, length 0
19:06:32.409175 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [S], seq 1837710426, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3624150644 ecr 0,sackOK,eol], length 0
19:06:32.485033 IP 192.168.0.50.http > 192.168.0.4.50903: Flags [S.], seq 849648316, ack 1837710427, win 5760, options [mss 1436], length 0
19:06:32.485199 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:32.486178 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [P.], seq 1:236, ack 1, win 65535, length 235: HTTP: GET / HTTP/1.1
19:06:32.543490 IP 192.168.0.50.http > 192.168.0.4.50903: Flags [.], ack 236, win 5525, length 0
19:06:32.577909 IP 192.168.0.50.http > 192.168.0.4.50903: Flags [P.], seq 1:596, ack 236, win 5525, length 595: HTTP: HTTP/1.1 200 OK
19:06:32.578021 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [.], ack 596, win 65535, length 0
19:06:32.579822 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [F.], seq 236, ack 596, win 65535, length 0
19:06:32.587010 IP 192.168.0.50.http > 192.168.0.4.50903: Flags [F.], seq 596, ack 237, win 5524, length 0
19:06:32.587118 IP 192.168.0.4.50903 > 192.168.0.50.http: Flags [.], ack 597, win 65535, length 0
19:06:39.722363 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [S], seq 2790428240, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2547270288 ecr 0,sackOK,eol], length 0
19:06:39.747009 IP 192.168.0.50.http > 192.168.0.4.50959: Flags [S.], seq 3387562555, ack 2790428241, win 5760, options [mss 1436], length 0
19:06:39.747061 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:39.747336 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:39.763547 IP 192.168.0.50.http > 192.168.0.4.50959: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:39.763632 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:39.763763 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:39.765313 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [S], seq 2856943518, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 4023418736 ecr 0,sackOK,eol], length 0
19:06:39.792437 IP 192.168.0.50.http > 192.168.0.4.50959: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:39.792535 IP 192.168.0.4.50959 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:06:39.796744 IP 192.168.0.50.http > 192.168.0.4.50960: Flags [S.], seq 2457553815, ack 2856943519, win 5760, options [mss 1436], length 0
19:06:39.796918 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:39.797194 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:39.812166 IP 192.168.0.50.http > 192.168.0.4.50960: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:39.812200 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:39.812392 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:39.824701 IP 192.168.0.50.http > 192.168.0.4.50960: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:39.824901 IP 192.168.0.4.50960 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:06:49.722794 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [S], seq 4061250518, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 1356539580 ecr 0,sackOK,eol], length 0
19:06:49.820777 IP 192.168.0.50.http > 192.168.0.4.51036: Flags [S.], seq 1555451508, ack 4061250519, win 5760, options [mss 1436], length 0
19:06:49.820883 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:49.821125 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:49.835300 IP 192.168.0.50.http > 192.168.0.4.51036: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:49.835446 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:49.835707 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:49.838228 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [S], seq 1927079567, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 1742669337 ecr 0,sackOK,eol], length 0
19:06:49.841633 IP 192.168.0.50.http > 192.168.0.4.51036: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:49.841775 IP 192.168.0.4.51036 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:06:49.852997 IP 192.168.0.50.http > 192.168.0.4.51038: Flags [S.], seq 2979412763, ack 1927079568, win 5760, options [mss 1436], length 0
19:06:49.853171 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:49.853775 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:49.865677 IP 192.168.0.50.http > 192.168.0.4.51038: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:49.865750 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:49.866082 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:49.875133 IP 192.168.0.50.http > 192.168.0.4.51038: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:49.875320 IP 192.168.0.4.51038 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:06:58.629343 ARP, Request who-has fritz.box tell 192.168.0.50, length 46
19:06:59.724089 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [S], seq 2070831457, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 2049651864 ecr 0,sackOK,eol], length 0
19:06:59.821524 IP 192.168.0.50.http > 192.168.0.4.51126: Flags [S.], seq 2036370906, ack 2070831458, win 5760, options [mss 1436], length 0
19:06:59.821658 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:59.822106 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:59.839607 IP 192.168.0.50.http > 192.168.0.4.51126: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:59.839762 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:59.840015 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:59.842752 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [S], seq 1294853534, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 3804398720 ecr 0,sackOK,eol], length 0
19:06:59.856657 IP 192.168.0.50.http > 192.168.0.4.51126: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:59.856843 IP 192.168.0.4.51126 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:06:59.863186 IP 192.168.0.50.http > 192.168.0.4.51129: Flags [S.], seq 1288937483, ack 1294853535, win 5760, options [mss 1436], length 0
19:06:59.863331 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:06:59.863694 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:06:59.875070 IP 192.168.0.50.http > 192.168.0.4.51129: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:06:59.875181 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:06:59.875370 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:06:59.881405 IP 192.168.0.50.http > 192.168.0.4.51129: Flags [F.], seq 672, ack 114, win 5647, length 0
19:06:59.881594 IP 192.168.0.4.51129 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:07:09.722784 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [S], seq 2017285915, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 782362797 ecr 0,sackOK,eol], length 0
19:07:09.848233 IP 192.168.0.50.http > 192.168.0.4.51200: Flags [S.], seq 3372312851, ack 2017285916, win 5760, options [mss 1436], length 0
19:07:09.848320 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:07:09.848714 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:07:09.861713 IP 192.168.0.50.http > 192.168.0.4.51200: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:07:09.861767 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:07:09.862007 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:07:09.863533 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [S], seq 2948523781, win 65535, options [mss 1460,nop,wscale 6,nop,nop,TS val 566719893 ecr 0,sackOK,eol], length 0
19:07:09.887060 IP 192.168.0.50.http > 192.168.0.4.51200: Flags [F.], seq 672, ack 114, win 5647, length 0
19:07:09.887286 IP 192.168.0.4.51200 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0
19:07:09.890960 IP 192.168.0.50.http > 192.168.0.4.51201: Flags [S.], seq 688110283, ack 2948523782, win 5760, options [mss 1436], length 0
19:07:09.891120 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [.], ack 1, win 65535, length 0
19:07:09.891419 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [P.], seq 1:113, ack 1, win 65535, length 112: HTTP: GET /api/livedata/status HTTP/1.1
19:07:09.905995 IP 192.168.0.50.http > 192.168.0.4.51201: Flags [P.], seq 1:672, ack 113, win 5648, length 671: HTTP: HTTP/1.1 200 OK
19:07:09.906088 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [.], ack 672, win 65535, length 0
19:07:09.906437 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [F.], seq 113, ack 672, win 65535, length 0
19:07:09.915787 IP 192.168.0.50.http > 192.168.0.4.51201: Flags [F.], seq 672, ack 114, win 5647, length 0
19:07:09.915952 IP 192.168.0.4.51201 > 192.168.0.50.http: Flags [.], ack 673, win 65535, length 0

```

**Comment by knxhm** [comment]
There is no any packet with port 1883. Hence no MQTT traffic at all.
Is MQTT enabled? Maybe switch was disabled by accident ? Switch status not visible in your screenshot.
Did you restart the esp32 while the trace was running?

If all good, there may be some corruption. I recommend to make a backup of config and pin mapping, erase the esp32, flash it again and restore the config and pin mapping.

**Comment by Rene1695** [comment]
@knxhm MQTT is turned on. I also set and reset the switch multiple times, since this was also helpful in the past. But now he is not connecting anymore. 

And yes I did a restart for the log capture. I noticed on the main screen that there were multiple time synchronizations. Someone once mentioned that MQTT does require a working NTP. Do you think there could be something wrong? Currently NTP is set to my router IP, but I also tried google. 

However, I will try to reset the esp in the next days and report the outcome. Thank you very much so far!!

**Comment by knxhm** [comment]
I tested on my installation, I set a nonworking NTP server IP. Then rebooted ESP32. The MQTT works as before and reports e.g. uptime. But the inverters are not queried. until at least you synchronize time manually from menu settings - ntp setting , button synchronize time.
So no, NTP is not required for MQTT to work, but syncronized time is required to query the inverters.

**Comment by solarfreddy** [comment]
I have the same problem with v25.4.10
It was running many months and now showing offline. Sometimes it gets some data for a few hours and then loses connection.
Time is synchronized (maybe 2sec difference) Manually synchronizing did not help. Also restarting esp32 did not help.
Wlan informatoin access point is not active for some reason.

**Comment by Boldfor** [comment]
> +1
> 
> Not 100% sure on the error, but I have multiple MQTT-components feeding into my openHAB, and everything is working, **except openDTU** (which has been running for 2 years without ever having a problem, ..., so it's the first time that openDTU causes problems).

**Update: My problem is solved.** Not sure about the root cause of the problem, but openDTU/MQTT was fine. Just the linkeage between openDTU and openHAB was gone. Whether this was because by the MQTT-names of openDTU being changed, or if openHAB changed anything, I cannot say.

**Comment by Rene1695** [comment]
@knxhm I finally found time to flash my ESP again. I also swapped the controller to an WT32-ETH0. Flashing was easily done and also the backup could be loaded. 

Now. MQTT is working again (it says connected and I can see some base data in the MQTT explorer). However, OpenDTU can not connect and communicate with my Homilies HM-600 anymore. In the logs, there is only a message for the system temperature, there is no data received from the inverter. What I tried out so far: 

1. Multiple restarts of OpenDTU as well as the inverter itself
2. Delete the Inverter and added a new Inverter with the same serial number 
3. Checked the NRF settings and pin mapping. On system page it says "successful connected to NRF24L0+"
4. Buy a new NRF24L0+ Module 
5. Placed the OpenDTU and NRF Module at different locations also directly next to the inverter

Any ideas what's wrong here? Is there a way to reset the Homiles? Should I stop using the backup file and do a clean new set up?

**Comment by knxhm** [comment]
> Any ideas what's wrong here? Is there a way to reset the Homiles? Should I stop using the backup file and do a clean new set up?

Clean new setup is worth to try, especially because I understand you have another board and these board runs another build variant of OpenDTU. And the board has quite a different pinout and many GPIO are used for the LAN chip, are you sure you wired it correctly and have the matching pinmapping profile settings?

If you dont succeed with the new board, I would try to reflash the old one, where you had a definitely working wiring. 
And dont forget to completely erase the flash before reflashing, to clear it from anything potentially harmful from before.

**Comment by Rene1695** [comment]
@knxhm So I have reflashed my old ESP32 which was working for 2 years. I did it multiple times also with erasing the chip. I did not put a backup in it, clean fresh reinstall. The NRF Modul is showing "connected" and "confuigured" all successful. I also tried multiple different NRF24 modules. 

Still the same issue. I can not reach any data from my homilies anymore. I know that my inverter is working, since I can see negative current values at my home grid. On the dashboard of OpenDTU it shows "nothing received" at the wireless statistics. 

Do you have any idea what I could test next? Are these NRF modules still recommended or are there more reliable alternatives?

**Comment by stefan123t** [comment]
Without a backup you may have to reconfigure most of the OpenDTU settings including WiFi, NTP and Inverters. The pin_mapping.json and the selected pin mapping in it seem to work for the NRF24L01+ in your build, but have you used low/min mode settings for the PA+LNA amplification ?

**Comment by Rene1695** [comment]
@stefan123t I did. I set up Wifi,  NTP and inverter settings manually again which isn't that much of settings (inverter serial number, router IP for NTP and my Wifi-Credentials). 

What do you mean with low/min mode? Do you mean the signal strength setting? 

<img width="2774" height="644" alt="Image" src="https://github.com/user-attachments/assets/dd933bfa-cf2a-42c6-9973-1bc60166e277" />

**Comment by stefan123t** [comment]
Yes I had problems in the past with some of the NRF modules, raising the transmit power to high/max would degrade the signal quality / prevent transmission at all.

But this does not look like your issue.

I reread your whole thread and I would compare the previous working config.json with the current setup/backup eg using diff.

What board and NRF chip are you using and which image did you flash. Does it require a factory reset / firmware as the partition layout on the SPIFFS has changed, see breaking changes. At least ODoB requires a larger ESP32-S3 since some months. Though OpenDTU should still run on any/most ESP32 modules afaik. Though you may need the 4M / No OTA version ?

And as @knxhm mentioned do you have other Peripherals which may conflict with the current setup. I.e. Network modules or PSRAM chips and/or anything else ?

**Comment by RKeme** [comment]
As it started with MQTT issues - did you try already without - so just basics?
